/**
 * Public composer API — builds Neo4j Cypher and SQLite from QUERY package objects.
 */

import { composePackage } from "./compose/package.js";
import { composeQuery } from "./compose/query.js";
import { buildExistsInstanceCondition } from "./exists.js";
import { nodePropertiesForCypher, relationshipPropertiesForCypher } from "./entity/properties.js";
import { escapeSqliteString, formatLiteral } from "./literals.js";
import { renderNode } from "./render/node.js";
import { hopSplit, hopTailVariables, renderPath, supportsHopSplit } from "./render/path.js";
import { renderRelationship } from "./render/relationship.js";
import { normalizeWhere, renderWhereGroup } from "./render/where.js";
import {
  composeQueriesCatalogUpsertSql,
  composeSequenceCatalogUpsertSql,
  composeSpaceLabelsUpdateSql
} from "./sqlite/catalog.js";
import { composeEntitySqlite, composeStepEntitySqlite } from "./sqlite/entity.js";
import {
  composeOneStepSequenceCypher,
  composeStepWrapEntitySql,
  composeStepWrapGraphCypher,
  isStepCodeExecution,
  isStepCustomEndpoint,
  isStepLocalLlm
} from "./step/endpoint.js";
import { instanceCreateIdParamName } from "./entity/ids.js";
import {
  autoGeneratedIdParameterNames,
  queryParametersForQueriesCatalog
} from "./step/parameters.js";
import {
  composeVectorSearchLines,
  isVectorSearchAllLabels,
  isVectorSearchEnabled,
  normalizeVectorK,
  vectorKLiteral,
  vectorKParameterName,
  vectorTextParameterName,
  VECTOR_PARAM_K,
  VECTOR_PARAM_TEXT,
  VECTOR_RESERVED_PARAM_NAMES,
  VECTOR_SEARCH_DEFAULT_K,
  VECTOR_SEARCH_MAX_K,
} from "./render/vectorSearch.js";
import type {
  ComposedQuery,
  CypherConditionBuilder,
  QueryObject,
  SequencialProperties
} from "./types.js";

export {
  composeVectorSearchLines,
  isVectorSearchAllLabels,
  isVectorSearchEnabled,
  normalizeVectorK,
  vectorKLiteral,
  vectorKParameterName,
  vectorTextParameterName,
  VECTOR_PARAM_K,
  VECTOR_PARAM_TEXT,
  VECTOR_RESERVED_PARAM_NAMES,
  VECTOR_SEARCH_DEFAULT_K,
  VECTOR_SEARCH_MAX_K,
};

// Hop-mode rules: which clauses may split a path, and which variables the split
// tails bind. Shared with @pona-flow/authoring so its validation and binding
// pickers cannot drift from what the composer actually emits.
export { hopSplit, hopTailVariables, supportsHopSplit };
export type { HopSplitMode, HopTailVariables } from "./render/path.js";

export type {
  Operation,
  GraphNodeLabel,
  DataType,
  ValueType,
  StringFormat,
  ConditionType,
  HttpMethod,
  WhereOperator,
  AliasMode,
  SchematicProperties,
  PropertyBinding,
  GraphIdBinding,
  StepType,
  CodeLanguage,
  SequencialProperties,
  StepResponseParameter,
  CypherConditionPredicate,
  CypherConditionBuilder,
  NodePattern,
  RelationshipLength,
  RelationshipPattern,
  PathElement,
  GraphPattern,
  MatchClause,
  WhereComparisonOperator,
  WhereFilter,
  WhereCondition,
  WhereGroup,
  WhereItem,
  ReturnItem,
  OrderByItem,
  SetValueMode,
  SetItem,
  DeleteClause,
  LiteralOrParameter,
  Parameter,
  ReturnClause,
  QueryObject,
  VectorSearchConfig,
  ComposedQuery,
} from "./types.js";

export { GRAPH_NODE_LABELS, GRAPH_REL_TYPE } from "./types.js";

export interface ComposerApi {
  composeQuery(query: QueryObject): ComposedQuery;
  composePackage(pkg: { queries: QueryObject[] }): {
    cypher: string;
    parametersByQuery: Array<{
      id: string;
      name: string;
      operation: string;
      cypher: string;
      parameters: Record<string, unknown>;
    }>;
  };
  composeEntitySqlite(query: QueryObject, operation?: string): string[];
  composeStepEntitySqlite(query: QueryObject, operation?: string): string[];
  composeSpaceLabelsUpdateSql(
    spaceId: string,
    existingLabels: string[],
    attributiveLabelsToAdd: string[]
  ): string | null;
  composeQueriesCatalogUpsertSql(
    pkg: {
      id: string;
      name: string;
      operation: string;
      node_label?: string;
      label?: string;
      cypher: string;
      sqlite: string[];
      parameters: unknown[];
    },
    runtimeEnabled: boolean
  ): string | null;
  composeSequenceCatalogUpsertSql(
    pkg: {
      id: string;
      name: string;
      cypher: string;
      parameters: unknown[];
      groupTitle?: string;
    }
  ): string | null;
  queryParametersForQueriesCatalog(query: QueryObject): Array<Record<string, unknown>>;
  autoGeneratedIdParameterNames(query: QueryObject): string[];
  instanceCreateIdParamName: typeof instanceCreateIdParamName;
  isStepCustomEndpoint(
    sp: { query_id?: string; endpoint?: string; body?: unknown } | null | undefined
  ): boolean;
  isStepCodeExecution(sp: SequencialProperties | null | undefined): boolean;
  isStepLocalLlm(sp: SequencialProperties | null | undefined): boolean;
  composeStepWrapEntitySql(params: {
    entityId: string;
    operationId: string;
    name: string;
  }): string[] | null;
  composeStepWrapGraphCypher(params: {
    entityId: string;
    operationId: string;
    name: string;
  }): string[] | null;
  composeOneStepSequenceCypher(params: { name: string }): string | null;
  escapeSqliteString(value: unknown): string;
  formatLiteral(value: unknown): string;
  buildExistsInstanceCondition(builder: CypherConditionBuilder): string;
  nodePropertiesForCypher: typeof nodePropertiesForCypher;
  relationshipPropertiesForCypher: typeof relationshipPropertiesForCypher;
  renderNode: typeof renderNode;
  renderRelationship: typeof renderRelationship;
  renderPath: typeof renderPath;
  normalizeWhere: typeof normalizeWhere;
  renderWhereGroup: typeof renderWhereGroup;
}

export const composer: ComposerApi = {
  composeQuery,
  composePackage,
  composeStepEntitySqlite,
  composeEntitySqlite,
  composeSpaceLabelsUpdateSql,
  composeQueriesCatalogUpsertSql,
  composeSequenceCatalogUpsertSql,
  queryParametersForQueriesCatalog,
  autoGeneratedIdParameterNames,
  instanceCreateIdParamName,
  isStepCustomEndpoint,
  isStepCodeExecution,
  isStepLocalLlm,
  composeStepWrapEntitySql,
  composeStepWrapGraphCypher,
  composeOneStepSequenceCypher,
  formatLiteral,
  escapeSqliteString,
  buildExistsInstanceCondition,
  nodePropertiesForCypher,
  relationshipPropertiesForCypher,
  renderNode,
  renderRelationship,
  renderPath,
  normalizeWhere,
  renderWhereGroup,
};

export default composer;
