/** Query parameter serialization for catalog and entity rows. */

import { instanceCreateIdParamName } from "../entity/ids.js";
import { escapeSqliteString } from "../literals.js";
import { isStepCustomEndpoint } from "./endpoint.js";
import {
  isVectorSearchEnabled,
  vectorKLiteral,
  vectorKParameterName,
  vectorTextParameterName,
  VECTOR_PARAM_K,
  VECTOR_PARAM_TEXT,
} from "../render/vectorSearch.js";
import type { Parameter, QueryObject, SequencialProperties } from "../types.js";

function parameterValueType(p: Parameter): string {
  const schemaType = p.schematic_properties?.value_type;
  if (schemaType && String(schemaType).trim()) return String(schemaType).trim();
  const legacyType = p.data_type;
  if (legacyType && String(legacyType).trim()) return String(legacyType).trim();
  return "string";
}

function normalizeChoiceOptions(options: unknown): string[] {
  if (!Array.isArray(options)) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const opt of options) {
    const t = String(opt ?? "").trim();
    if (!t || seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  return out;
}

export function serializeQueryParametersArray(parameters: Parameter[] | null | undefined) {
  return (parameters || [])
    .filter((p) => p && p.name)
    .map((p) => {
      const value_type = parameterValueType(p);
      const sp = p.schematic_properties;
      const row: Record<string, unknown> = {
        name: String(p.name),
        value_type,
        value: p.value,
        is_required: Boolean(p.is_required),
      };
      if (value_type === "string" && sp?.format) {
        row.format = sp.format;
      }
      if (value_type === "radio" || value_type === "checkbox") {
        row.options = normalizeChoiceOptions(sp?.options);
        if (value_type === "checkbox") {
          if (typeof sp?.min_choices === "number") row.min_choices = sp.min_choices;
          if (typeof sp?.max_choices === "number") row.max_choices = sp.max_choices;
        }
      }
      const description = typeof p.description === "string" ? p.description.trim() : "";
      if (description) {
        row.description = description;
      }
      return row;
    });
}

/**
 * Names of the run-time-minted id parameters a create-INSTANCE query binds
 * (``id__<variable>``, one per created node/relationship with an engine-minted id).
 */
export function autoGeneratedIdParameterNames(query: QueryObject | null | undefined): string[] {
  const names: string[] = [];
  if (!query || (query.operation || "") !== "create") return names;
  const seen = new Set<string>();
  (query.match || []).forEach((clause) => {
    if ((clause.label || "") !== "INSTANCE") return;
    (clause.patterns || []).forEach((pattern) => {
      (pattern.path || []).forEach((el) => {
        const entity = el.kind === "node" ? el.node : el.relationship;
        const name = instanceCreateIdParamName(entity, {
          clauseLabel: "INSTANCE",
          operation: "create",
          entityKind: el.kind === "node" ? "node" : "relationship",
        });
        if (name && !seen.has(name)) {
          seen.add(name);
          names.push(name);
        }
      });
    });
  });
  return names;
}

export function queryParametersForQueriesCatalog(query: QueryObject | null | undefined) {
  // The queries-catalog `parameters` column always mirrors the builder's defined
  // parameters. STEP custom-endpoint nodes also persist a copy on their entity row
  // (see entityParametersSql), but that must not blank out the catalog column.
  const rows = serializeQueryParametersArray(query && query.parameters);
  // Run-time-minted create ids are declared with auto_generate so the executor mints
  // a fresh UID per run (and the run panel / MCP schema can hide them from humans).
  const declared = new Set(rows.map((r) => String(r.name)));
  for (const name of autoGeneratedIdParameterNames(query ?? null)) {
    if (declared.has(name)) continue;
    rows.push({
      name,
      value_type: "UID",
      value: "",
      is_required: false,
      auto_generate: true,
    });
  }
  // Vector search: a literal text/k is authored on QueryObject.vector_search rather than
  // in query.parameters (which would disable the builder Run button), so declare it here
  // under the reserved name. A parameterized one is already a row from the author's own
  // $name; tag it with vector_role so the engine knows which value to embed or limit by.
  if (query && isVectorSearchEnabled(query)) {
    const byName = new Map(rows.map((r) => [String(r.name), r]));
    const textParameter = vectorTextParameterName(query);
    if (textParameter) {
      const row = byName.get(textParameter);
      if (row) row.vector_role = "text";
    } else if (!declared.has(VECTOR_PARAM_TEXT)) {
      rows.push({
        name: VECTOR_PARAM_TEXT,
        value_type: "string",
        value: String(query.vector_search!.text ?? ""),
        is_required: true,
        description: "Free-text query for nearest-neighbour vector search.",
      });
      declared.add(VECTOR_PARAM_TEXT);
    }
    const kParameter = vectorKParameterName(query);
    if (kParameter) {
      const row = byName.get(kParameter);
      if (row) row.vector_role = "k";
    } else if (!declared.has(VECTOR_PARAM_K)) {
      rows.push({
        name: VECTOR_PARAM_K,
        value_type: "integer",
        value: vectorKLiteral(query),
        is_required: false,
        description: "Number of nearest neighbours to return (1–100).",
      });
      declared.add(VECTOR_PARAM_K);
    }
  }
  return rows;
}

export function entityParametersSql(
  query: QueryObject,
  clauseLabel: string,
  sequencialProperties: SequencialProperties | null | undefined
): string {
  if (clauseLabel === "STEP" && isStepCustomEndpoint(sequencialProperties)) {
    return escapeSqliteString(JSON.stringify(serializeQueryParametersArray(query.parameters)));
  }
  return escapeSqliteString("[]");
}
